import type { UIMessageStreamWriter, UIMessage } from 'ai'
import type { DataPart } from '../messages/data-parts'
import { getContents, type File } from './generate-files/get-contents'
import { getRichError } from './get-rich-error'
import { tool } from 'ai'
import description from './generate-files.md'
import z from 'zod/v3'
import { GenerationSessionTracker } from '@/lib/generation-session-tracker'
import { storePendingDiffs, buildDiffSummary, type PendingDiffFile } from '@/lib/diff'
import { randomUUID } from 'crypto'

interface Params {
  modelId: string
  writer: UIMessageStreamWriter<UIMessage<never, DataPart>>
  sessionTracker?: GenerationSessionTracker | null
  projectId?: string | null
  sessionId?: string
}

export const generateFiles = ({ writer, modelId, sessionTracker, projectId, sessionId }: Params) =>
  tool({
    description,
    inputSchema: z.object({
      sandboxId: z.string(),
      paths: z.array(z.string()),
    }),
    execute: async ({ sandboxId, paths }, { toolCallId, messages }) => {
      if (sessionTracker) {
        const isCancelled = await GenerationSessionTracker.isCancelled(sessionTracker.id)
        if (isCancelled) {
          throw new Error('Generation cancelled')
        }
        await sessionTracker.updateProgress({
          stage: 'generating',
          message: 'Generating files',
          paths: [],
          filesCount: 0,
          completionPercentage: 30,
        })
      }

      writer.write({
        id: toolCallId,
        type: 'data-generating-files',
        data: { paths: [], status: 'generating' },
      })

      const iterator = getContents({ messages, modelId, paths })
      const allFiles: File[] = []

      // Collect all generated files
      try {
        for await (const chunk of iterator) {
          if (sessionTracker) {
            const isCancelled = await GenerationSessionTracker.isCancelled(sessionTracker.id)
            if (isCancelled) {
              await sessionTracker.updateProgress({
                stage: 'done',
                message: 'Generation cancelled',
                completionPercentage: 100,
              })
              throw new Error('Generation cancelled')
            }
          }

          if (chunk.files.length > 0) {
            allFiles.push(...chunk.files)
            if (sessionTracker) {
              await sessionTracker.updateProgress({
                stage: 'generating',
                message: 'Preparing files for review',
                paths: allFiles.map((f) => f.path),
                filesCount: allFiles.length,
                completionPercentage: 30 + Math.min(50, allFiles.length * 5),
              })
            }
          } else {
            if (sessionTracker) {
              await sessionTracker.updateProgress({
                stage: 'generating',
                message: 'Preparing file contents',
                paths: chunk.paths,
                filesCount: allFiles.length,
                completionPercentage: 30,
              })
            }

            writer.write({
              id: toolCallId,
              type: 'data-generating-files',
              data: { status: 'generating', paths: chunk.paths },
            })
          }
        }
      } catch (error) {
        const richError = getRichError({
          action: 'generate file contents',
          args: { modelId, paths },
          error,
        })

        writer.write({
          id: toolCallId,
          type: 'data-generating-files',
          data: { error: richError.error, status: 'error', paths },
        })

        return richError.message
      }

      if (allFiles.length === 0) {
        writer.write({
          id: toolCallId,
          type: 'data-generating-files',
          data: { paths: [], status: 'done' },
        })
        return 'No files were generated.'
      }

      // ── Stage files as pending diffs (diff preview before writing to E2B) ──
      writer.write({
        id: toolCallId,
        type: 'data-generating-files',
        data: { paths: allFiles.map((f) => f.path), status: 'validating' },
      })

      const pendingDiffs: PendingDiffFile[] = allFiles.map((file) => ({
        path: file.path,
        action: 'create' as const,
        content: file.content,
        description: `Generated by AI`,
      }))

      const summary = buildDiffSummary(pendingDiffs)
      const effectiveProjectId = projectId ?? 'unknown'
      const effectiveSessionId = sessionId ?? randomUUID()

      let pendingId: string | null = null
      try {
        pendingId = await storePendingDiffs({
          sessionId: effectiveSessionId,
          projectId: effectiveProjectId,
          sandboxId,
          diffs: pendingDiffs,
          summary,
        })
      } catch (err) {
        console.warn('[generate-files] Failed to store pending diffs — falling back to direct write:', err)
      }

      // Stream file contents to Monaco editor so user can preview immediately
      for (const file of allFiles) {
        writer.write({
          id: toolCallId,
          type: 'data-file-content',
          data: { sandboxId, path: file.path, content: file.content },
        })
      }

      if (pendingId) {
        // Emit pending-diff event: user must approve before files are written to E2B
        writer.write({
          type: 'data-pending-diff',
          data: {
            pendingId,
            sandboxId,
            sessionId: effectiveSessionId,
            projectId: effectiveProjectId,
            diffs: pendingDiffs,
            totalFiles: pendingDiffs.length,
            summary,
          },
        } as never)

        if (sessionTracker) {
          await sessionTracker.updateProgress({
            stage: 'validating',
            message: 'Waiting for user to review changes',
            paths: allFiles.map((f) => f.path),
            filesCount: allFiles.length,
            completionPercentage: 85,
          })
        }

        return `Generated ${allFiles.length} files. They have been staged for review (pendingId: ${pendingId}). The user will review and approve the changes before they are written to the sandbox. Do NOT call runCommand or getSandboxUrl — wait for the user to approve.`
      }

      // Fallback: pending diff storage failed, write directly
      const { Sandbox } = await import('e2b')
      let sandbox
      try {
        sandbox = await Sandbox.connect(sandboxId, { apiKey: process.env.E2B_API_KEY })
      } catch (error) {
        const richError = getRichError({ action: 'connect to sandbox by id', args: { sandboxId }, error })
        writer.write({ id: toolCallId, type: 'data-generating-files', data: { error: richError.error, paths: [], status: 'error' } })
        return richError.message
      }

      for (const file of allFiles) {
        await sandbox.files.write(file.path, file.content)
      }

      writer.write({
        id: toolCallId,
        type: 'data-generating-files',
        data: { paths: allFiles.map((f) => f.path), status: 'done' },
      })

      if (sessionTracker) {
        await sessionTracker.updateProgress({
          stage: 'validating',
          message: 'Files generated. Validating project...',
          paths: allFiles.map((f) => f.path),
          filesCount: allFiles.length,
          completionPercentage: 92,
        })
      }

      return `Successfully generated and uploaded ${allFiles.length} files: ${allFiles.map((f) => f.path).join(', ')}`
    },
  })
