import type { Sandbox } from '@vercel/sandbox'
import { listEnvVars } from '@/lib/env-vars-db'
import { getProject } from '@/lib/projects-db'

function escapeEnvValue(value: string) {
  const normalized = value.replace(/\r\n/g, '\n')

  const needsQuotes =
    normalized.length === 0 ||
    /\s/.test(normalized) ||
    /["'`$\\#=]/.test(normalized) ||
    normalized.includes('\n')

  if (!needsQuotes) return normalized

  return (
    '"' +
    normalized
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n') +
    '"'
  )
}

function buildDotEnvFile(vars: { key: string; value: string }[]) {
  const header =
    '# Generated by Thinksoft. Do not commit this file.\n' +
    '# These values come from the project Environment Variables tab.\n\n'

  const lines = vars
    .filter((v) => v.key && typeof v.value === 'string')
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((v) => `${v.key}=${escapeEnvValue(v.value)}`)

  return header + lines.join('\n') + (lines.length ? '\n' : '')
}

export async function syncProjectEnvToSandbox(params: {
  sandbox: Sandbox
  userId?: string
  projectId?: string
}) {
  const { sandbox, userId, projectId } = params
  if (!userId || !projectId) return

  const project = await getProject(userId, projectId)
  if (!project) return

  const envVars = await listEnvVars(projectId)
  if (envVars.length === 0) return

  const content = buildDotEnvFile(envVars.map((v) => ({ key: v.key, value: v.value })))

  await sandbox.writeFiles([
    { path: '.env.local', content: Buffer.from(content, 'utf8') },
    { path: '.env', content: Buffer.from(content, 'utf8') },
  ])
}
